services:
  mumei-bot:
    build: .
    container_name: mumei-bot
    image: aishukander/mumei-bot
    restart: unless-stopped
    volumes:
      - ./toml:/bot/toml
      - ./CallPicture:/bot/CallPicture