searches = [
]
url = "https://www.mvdis.gov.tw/m3-emv-trn/exm/locations#"

[stations]
"士林監理站" = "21"
"基隆監理站" = "25"
"金門監理站" = "26"
"連江監理站" = "28"
"高雄市區監理所" = "30"
"苓雅監理站" = "31"
"旗山監理站" = "33"
"臺北區監理所" = "40"
"板橋監理站" = "41"
"宜蘭監理站" = "43"
"花蓮監理站" = "44"
"玉里監理分站" = "45"
"蘆洲監理站" = "46"
"新竹區監理所" = "50"
"新竹市監理站" = "51"
"桃園監理站" = "52"
"中壢監理站" = "53"
"苗栗監理站" = "54"
"臺中區監理所" = "60"
"豐原監理站" = "63"
"彰化監理站" = "64"
"南投監理站" = "65"
"埔里監理分站" = "62"
"嘉義區監理所" = "70"
"臺南監理站" = "74"
"麻豆監理站" = "75"
"新營監理站" = "73"
"雲林監理站" = "72"
"東勢監理分站" = "71"
"嘉義市監理站" = "76"
"臺中市監理站" = "61"
"高雄區監理所" = "80"
"臺東監理站" = "81"
"屏東監理站" = "82"
"恆春監理分站" = "83"
"澎湖監理站" = "84"
